version: '3.7'
# Any top-level key starting with x- in a Docker Compose file will be
# ignored
x-backend: &common  # yaml anchor definition
  image: papermerge:2.1.8
  volumes:
    - media_root:/app/media
  environment:
    - PAPERMERGE__MAIN__SECRET_KEY=abc
    - DJANGO_SUPERUSER_PASSWORD=123
    - PAPERMERGE__REDIS__HOST=redis
    - PAPERMERGE__REDIS__PORT=6379
    - PAPERMERGE__DATABASE__TYPE=postgres
    - PAPERMERGE__DATABASE__USER=postgres
    - PAPERMERGE__DATABASE__NAME=postgres
    - PAPERMERGE__DATABASE__PASSWORD=postgres
    - PAPERMERGE__DATABASE__HOST=db
    - PAPERMERGE__DATABASE__PORT=5432
    - PAPERMERGE__SEARCH__ENGINE=elastic7
    - PAPERMERGE__SEARCH__URL=http://es:9200
services:
  backend:
    <<: *common
    ports:
      - '8000:8000'
  worker:
    <<: *common
    command: worker
  redis:
    image: redis:6
    ports:
      - '6379:6379'
  db:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  media_root:
  postgres_data:
