name: Build/Pub Image

on: [workflow_dispatch]


jobs:
  build-and-push-image-to-docker-hub:
    name: Build/Pub to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: papermerge/base

      - name: Build and push with MANUAL tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: papermerge/base
          file: Dockerfile
