name: Dockerhub

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
      INCLUDE_ARM64_PLATFORM:
        description: 'Also build for arm64 (DockerHub only)'
        type: boolean
        required: true
        default: true
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: string
      INCLUDE_ARM64_PLATFORM:
        description: 'Also build for arm64 (DockerHub only)'
        type: boolean
        required: true
        default: true

jobs:
  arm64-amd64:
    name: arm64/amd64
    runs-on: ubuntu-latest
    if: ${{ inputs.INCLUDE_ARM64_PLATFORM }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/base:latest,papermerge/base:${{ inputs.VERSION }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: papermerge/base

  amd64:
    name: amd64
    runs-on: ubuntu-latest
    if: ${{ !inputs.INCLUDE_ARM64_PLATFORM }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/base:latest,papermerge/base:${{ inputs.VERSION }}
          file: Dockerfile

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: papermerge/base
