name: Dockerhub

on:
  workflow_dispatch:
    inputs:
      BACKEND_TAG:
        required: true
        type: string
        default: latest-headless
      FRONTEND_TAG:
        required: true
        type: string
        default: latest
      IS_LATEST:
        type: boolean
        default: false
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      INPUT_BACKEND_TAG:
        required: true
        type: string
        default: latest-headless
      INPUT_FRONTEND_TAG:
        required: true
        type: string
        default: latest
      OUTPUT_TAG:
        required: true
        type: string
      IS_LATEST:
        type: boolean
        default: false

jobs:
  build-and-publish:
    name: papermerge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Papermerge ${{ inputs.OUTPUT_TAG }}
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.OUTPUT_TAG }}
          file: papermerge/Dockerfile
          build-args: frontend_tag=${{inputs.INPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}

      - name: Papermerge latest
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:latest
          file: papermerge/Dockerfile
          build-args: frontend_tag=${{inputs.FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}
        if: ${{ inputs.IS_LATEST == 'true' }}

      - name: Papermerge Bundle inputs.OUTPUT_TAG
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.OUTPUT_TAG }}-bundle
          file: bundle/Dockerfile
          build-args: frontend_tag=${{inputs.INTPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}

      - name: Papermerge Bundle Latest
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:latest-bundle
          file: bundle/Dockerfile
          build-args: frontend_tag=${{inputs.INPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}
        if: ${{ inputs.IS_LATEST == 'true' }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: papermerge/papermerge
