name: ghcr.io

on:
  workflow_dispatch:
    inputs:
      INPUT_BACKEND_TAG:
        required: true
        type: string
        default: latest-headless
      INPUT_FRONTEND_TAG:
        required: true
        type: string
        default: latest
      IS_LATEST:
        type: boolean
        default: false
  workflow_call:
    secrets:
      MY_GH_TOKEN:
        required: true
    inputs:
      INPUT_BACKEND_TAG:
        required: true
        type: string
        default: latest-headless
      INPUT_FRONTEND_TAG:
        required: true
        type: string
        default: latest
        type: string
      IS_LATEST:
        type: boolean
        default: false
jobs:
  build-and-publish:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Extract output
        id: get-output-tag
        run: |
          output_tag=$(echo ${{github.event.inputs.INPUT_BACKEND_TAG}} | cut -d- -f1)
          echo $output_tag
          echo "OUTPUT_TAG=$output_tag" >> $GITHUB_OUTPUT
      - run: echo "OUTPUT_TAG=${{ steps.get-output-tag.outputs.OUTPUT_TAG }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GH_TOKEN }}

      - name: Papermerge ${{ steps.get-output-tag.outputs.OUTPUT_TAG }}
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:${{ steps.get-output-tag.outputs.OUTPUT_TAG }}
          file: papermerge/Dockerfile
          build-args: |
            frontend_tag=${{github.event.inputs.INPUT_FRONTEND_TAG}}
            backend_tag=${{github.event.inputs.INPUT_BACKEND_TAG}}

      - name: Papermerge latest
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:latest
          file: papermerge/Dockerfile
          build-args: |
            frontend_tag=${{github.event.inputs.INPUT_FRONTEND_TAG}}
            backend_tag=${{github.event.inputs.INPUT_BACKEND_TAG}}
        if: ${{ inputs.IS_LATEST == 'true' }}
