name: ghcr.io

on:
  workflow_dispatch:
    inputs:
      INPUT_BACKEND_TAG:
        required: true
        type: string
        default: latest-headless
      INPUT_FRONTEND_TAG:
        required: true
        type: string
        default: latest
      OUTPUT_TAG:
        required: true
        type: string
      IS_LATEST:
        type: boolean
        default: false
  workflow_call:
    secrets:
      MY_GH_TOKEN:
        required: true
    inputs:
      INPUT_BACKEND_TAG:
        required: true
        type: string
        default: latest-headless
      INPUT_FRONTEND_TAG:
        required: true
        type: string
        default: latest
      OUTPUT_TAG:
        required: true
        type: string
      IS_LATEST:
        type: boolean
        default: false
jobs:
  amb64:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GH_TOKEN }}

      - name: Papermerge ${{ inputs.OUTPUT_TAG }}
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.OUTPUT_TAG }}
          file: papermerge/Dockerfile
          build-args: frontend_tag=${{inputs.INPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}

      - name: Papermerge latest
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:latest
          file: papermerge/Dockerfile
          build-args: frontend_tag=${{inputs.INPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}
        if: ${{ inputs.IS_LATEST == 'true' }}

      - name: Papermerge Bundle inputs.OUTPUT_TAG
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:${{ inputs.OUTPUT_TAG }}-bundle
          file: bundle/Dockerfile
          build-args: frontend_tag=${{inputs.INPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}

      - name: Papermerge Bundle Latest
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: papermerge/papermerge:latest-bundle
          file: bundle/Dockerfile
          build-args: frontend_tag=${{inputs.INPUT_FRONTEND_TAG}},backend_tag=${{inputs.INPUT_BACKEND_TAG}}
        if: ${{ inputs.IS_LATEST == 'true' }}
