name: ghcr.io

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
  workflow_call:
    secrets:
      MY_GH_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  amb64:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papermerge/base:${{ inputs.VERSION }},papermerge/base:latest
          file: Dockerfile